apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  generation: 20
  name: deployments
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    plugin:
      name: kpt-repo
    repoURL: https://github.com/alexvanboxel/deployments.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}